# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tulo/documents/v1/document_incoming.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/wrappers_pb'
require 'tulo/common/v1/response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tulo/documents/v1/document_incoming.proto", :syntax => :proto3) do
    add_message "tulo.documents.v1.DocumentsIncomingResponse" do
      repeated :documents_incoming, :message, 1, "tulo.documents.v1.DocumentIncoming"
    end
    add_message "tulo.documents.v1.UpsertDocumentIncomingRequest" do
      optional :document_incoming, :message, 1, "tulo.documents.v1.DocumentIncoming"
    end
    add_message "tulo.documents.v1.UpsertDocumentIncomingResponse" do
      optional :document_incoming, :message, 1, "tulo.documents.v1.DocumentIncoming"
    end
    add_message "tulo.documents.v1.DocumentIncomingIdRequest" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
    end
    add_message "tulo.documents.v1.DocumentIncomingResponse" do
      optional :document_incoming, :message, 1, "tulo.documents.v1.DocumentIncoming"
    end
    add_message "tulo.documents.v1.DocumentIncoming" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
      optional :document_name, :message, 2, "google.protobuf.StringValue"
      optional :document_type_id, :message, 3, "google.protobuf.Int64Value"
      optional :document_destination_id, :message, 4, "google.protobuf.Int64Value"
      optional :abstract, :message, 5, "google.protobuf.StringValue"
      optional :file_path, :message, 6, "google.protobuf.StringValue"
      optional :file_name, :message, 7, "google.protobuf.StringValue"
      optional :created_at, :message, 8, "google.protobuf.StringValue"
      optional :updated_at, :message, 9, "google.protobuf.StringValue"
    end
  end
end

module Tulo
  module Documents
    module V1
      DocumentsIncomingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentsIncomingResponse").msgclass
      UpsertDocumentIncomingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.UpsertDocumentIncomingRequest").msgclass
      UpsertDocumentIncomingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.UpsertDocumentIncomingResponse").msgclass
      DocumentIncomingIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentIncomingIdRequest").msgclass
      DocumentIncomingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentIncomingResponse").msgclass
      DocumentIncoming = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentIncoming").msgclass
    end
  end
end
