# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tulo/documents/v1/document_destination.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/wrappers_pb'
require 'tulo/common/v1/response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tulo/documents/v1/document_destination.proto", :syntax => :proto3) do
    add_message "tulo.documents.v1.DocumentDestinationsResponse" do
      repeated :document_destinations, :message, 1, "tulo.documents.v1.DocumentDestination"
    end
    add_message "tulo.documents.v1.UpsertDocumentDestinationRequest" do
      optional :document_destination, :message, 1, "tulo.documents.v1.DocumentDestination"
    end
    add_message "tulo.documents.v1.UpsertDocumentDestinationResponse" do
      optional :document_destination, :message, 1, "tulo.documents.v1.DocumentDestination"
    end
    add_message "tulo.documents.v1.DocumentDestinationIdRequest" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
    end
    add_message "tulo.documents.v1.DocumentDestinationResponse" do
      optional :document_destination, :message, 1, "tulo.documents.v1.DocumentDestination"
    end
    add_message "tulo.documents.v1.DocumentDestination" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
      optional :document_destination_name, :message, 2, "google.protobuf.StringValue"
      optional :email, :message, 3, "google.protobuf.StringValue"
      optional :phone, :message, 4, "google.protobuf.StringValue"
      optional :description, :message, 5, "google.protobuf.StringValue"
      optional :created_at, :message, 6, "google.protobuf.StringValue"
      optional :updated_at, :message, 7, "google.protobuf.StringValue"
    end
  end
end

module Tulo
  module Documents
    module V1
      DocumentDestinationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentDestinationsResponse").msgclass
      UpsertDocumentDestinationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.UpsertDocumentDestinationRequest").msgclass
      UpsertDocumentDestinationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.UpsertDocumentDestinationResponse").msgclass
      DocumentDestinationIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentDestinationIdRequest").msgclass
      DocumentDestinationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentDestinationResponse").msgclass
      DocumentDestination = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentDestination").msgclass
    end
  end
end
