# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tulo/documents/v1/document_type.proto for package 'tulo.documents.v1'

require 'grpc'
require 'tulo/documents/v1/document_type_pb'

module Tulo
  module Documents
    module V1
      module DocumentTypeService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tulo.documents.v1.DocumentTypeService'

          rpc :GetDocumentTypes, ::Google::Protobuf::Empty, ::Tulo::Documents::V1::DocumentTypesResponse
          rpc :GetDocumentTypeById, ::Tulo::Documents::V1::DocumentTypeIdRequest, ::Tulo::Documents::V1::DocumentTypeResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
