# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tulo/documents/v1/document_type.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tulo/documents/v1/document_type.proto", :syntax => :proto3) do
    add_message "tulo.documents.v1.DocumentTypesResponse" do
      repeated :document_types, :message, 1, "tulo.documents.v1.DocumentType"
    end
    add_message "tulo.documents.v1.DocumentTypeIdRequest" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
    end
    add_message "tulo.documents.v1.DocumentTypeResponse" do
      optional :document_type, :message, 1, "tulo.documents.v1.DocumentType"
    end
    add_message "tulo.documents.v1.DocumentType" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
      optional :document_type_name, :message, 2, "google.protobuf.StringValue"
      optional :description, :message, 3, "google.protobuf.StringValue"
    end
  end
end

module Tulo
  module Documents
    module V1
      DocumentTypesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentTypesResponse").msgclass
      DocumentTypeIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentTypeIdRequest").msgclass
      DocumentTypeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentTypeResponse").msgclass
      DocumentType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentType").msgclass
    end
  end
end
