# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tulo/documents/v1/document_incoming.proto for package 'tulo.documents.v1'

require 'grpc'
require 'tulo/documents/v1/document_incoming_pb'

module Tulo
  module Documents
    module V1
      module DocumentIncomingService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tulo.documents.v1.DocumentIncomingService'

          rpc :GetDocumentsIncoming, ::Google::Protobuf::Empty, ::Tulo::Documents::V1::DocumentsIncomingResponse
          rpc :UpsertDocumentIncoming, ::Tulo::Documents::V1::UpsertDocumentIncomingRequest, ::Tulo::Documents::V1::UpsertDocumentIncomingResponse
          rpc :GetDocumentIncomingById, ::Tulo::Documents::V1::DocumentIncomingIdRequest, ::Tulo::Documents::V1::DocumentIncomingResponse
          rpc :DeleteDocumentIncomingById, ::Tulo::Documents::V1::DocumentIncomingIdRequest, ::Tulo::Common::V1::CommonDeleteResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
