# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tulo/documents/v1/document_processing_time.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/wrappers_pb'
require 'tulo/common/v1/response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tulo/documents/v1/document_processing_time.proto", :syntax => :proto3) do
    add_message "tulo.documents.v1.DocumentProcessingTimesResponse" do
      repeated :document_processing_times, :message, 1, "tulo.documents.v1.DocumentProcessingTime"
    end
    add_message "tulo.documents.v1.UpsertDocumentProcessingTimeRequest" do
      optional :document_processing_time, :message, 1, "tulo.documents.v1.DocumentProcessingTime"
    end
    add_message "tulo.documents.v1.UpsertDocumentProcessingTimeResponse" do
      optional :document_processing_time, :message, 1, "tulo.documents.v1.DocumentProcessingTime"
    end
    add_message "tulo.documents.v1.DocumentProcessingTimeIdRequest" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
    end
    add_message "tulo.documents.v1.DocumentProcessingTimeResponse" do
      optional :document_processing_time, :message, 1, "tulo.documents.v1.DocumentProcessingTime"
    end
    add_message "tulo.documents.v1.RequestParams" do
      optional :document_type_id, :message, 1, "google.protobuf.Int64Value"
      optional :document_destination_id, :message, 2, "google.protobuf.Int64Value"
    end
    add_message "tulo.documents.v1.ProcessingTimeResponse" do
      optional :processing_time, :message, 1, "google.protobuf.Int32Value"
    end
    add_message "tulo.documents.v1.DocumentProcessingTime" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
      optional :document_type_id, :message, 2, "google.protobuf.Int64Value"
      optional :document_destination_id, :message, 3, "google.protobuf.Int64Value"
      optional :processing_time, :message, 4, "google.protobuf.Int32Value"
      optional :created_at, :message, 5, "google.protobuf.StringValue"
      optional :updated_at, :message, 6, "google.protobuf.StringValue"
    end
  end
end

module Tulo
  module Documents
    module V1
      DocumentProcessingTimesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentProcessingTimesResponse").msgclass
      UpsertDocumentProcessingTimeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.UpsertDocumentProcessingTimeRequest").msgclass
      UpsertDocumentProcessingTimeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.UpsertDocumentProcessingTimeResponse").msgclass
      DocumentProcessingTimeIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentProcessingTimeIdRequest").msgclass
      DocumentProcessingTimeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentProcessingTimeResponse").msgclass
      RequestParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.RequestParams").msgclass
      ProcessingTimeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.ProcessingTimeResponse").msgclass
      DocumentProcessingTime = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.documents.v1.DocumentProcessingTime").msgclass
    end
  end
end
