# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tulo/documents/v1/document_processing_time.proto for package 'tulo.documents.v1'

require 'grpc'
require 'tulo/documents/v1/document_processing_time_pb'

module Tulo
  module Documents
    module V1
      module DocumentProcessingTimeService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tulo.documents.v1.DocumentProcessingTimeService'

          rpc :GetDocumentProcessingTimes, ::Google::Protobuf::Empty, ::Tulo::Documents::V1::DocumentProcessingTimesResponse
          rpc :UpsertDocumentProcessingTime, ::Tulo::Documents::V1::UpsertDocumentProcessingTimeRequest, ::Tulo::Documents::V1::UpsertDocumentProcessingTimeResponse
          rpc :GetDocumentProcessingTimeById, ::Tulo::Documents::V1::DocumentProcessingTimeIdRequest, ::Tulo::Documents::V1::DocumentProcessingTimeResponse
          rpc :DeleteDocumentProcessingTimeById, ::Tulo::Documents::V1::DocumentProcessingTimeIdRequest, ::Tulo::Common::V1::CommonDeleteResponse
          rpc :GetProcessingTime, ::Tulo::Documents::V1::RequestParams, ::Tulo::Documents::V1::ProcessingTimeResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
