# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tulo/common/v1/master.proto for package 'tulo.common.v1'

require 'grpc'
require 'tulo/common/v1/master_pb'

module Tulo
  module Common
    module V1
      module MasterService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tulo.common.v1.MasterService'

          # --
          # common_003 Get Countries, Provinces and Districts
          # --
          rpc :GetCountriesProvincesDistricts, ::Google::Protobuf::Empty, ::Tulo::Common::V1::CountriesProvincesDistrictsResponse
          # --
          # common_004 Get Wards By District ID
          # --
          rpc :GetWardsByDistrictId, ::Tulo::Common::V1::DistrictIdRequest, ::Tulo::Common::V1::WardsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
