# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tulo/common/v1/response.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tulo/common/v1/response.proto", :syntax => :proto3) do
    add_message "tulo.common.v1.CommonDeleteResponse" do
      optional :message, :message, 1, "google.protobuf.BoolValue"
    end
  end
end

module Tulo
  module Common
    module V1
      CommonDeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.common.v1.CommonDeleteResponse").msgclass
    end
  end
end
