# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tulo/common/v1/role.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/wrappers_pb'
require 'tulo/common/v1/response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tulo/common/v1/role.proto", :syntax => :proto3) do
    add_message "tulo.common.v1.RolesResponse" do
      repeated :roles, :message, 1, "tulo.common.v1.Role"
    end
    add_message "tulo.common.v1.UpsertRoleRequest" do
      optional :role, :message, 1, "tulo.common.v1.Role"
    end
    add_message "tulo.common.v1.UpsertRoleResponse" do
      optional :role, :message, 1, "tulo.common.v1.Role"
    end
    add_message "tulo.common.v1.RoleIdRequest" do
      optional :role_id, :message, 1, "google.protobuf.StringValue"
    end
    add_message "tulo.common.v1.RoleResponse" do
      optional :role, :message, 1, "tulo.common.v1.Role"
    end
    add_message "tulo.common.v1.Role" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
      optional :role_id, :message, 2, "google.protobuf.StringValue"
      optional :role_name, :message, 3, "google.protobuf.StringValue"
      optional :description, :message, 4, "google.protobuf.StringValue"
      optional :created_at, :message, 5, "google.protobuf.StringValue"
      optional :updated_at, :message, 6, "google.protobuf.StringValue"
    end
  end
end

module Tulo
  module Common
    module V1
      RolesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.common.v1.RolesResponse").msgclass
      UpsertRoleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.common.v1.UpsertRoleRequest").msgclass
      UpsertRoleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.common.v1.UpsertRoleResponse").msgclass
      RoleIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.common.v1.RoleIdRequest").msgclass
      RoleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.common.v1.RoleResponse").msgclass
      Role = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.common.v1.Role").msgclass
    end
  end
end
