# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tulo/common/v1/role.proto for package 'tulo.common.v1'

require 'grpc'
require 'tulo/common/v1/role_pb'

module Tulo
  module Common
    module V1
      module RoleService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tulo.common.v1.RoleService'

          rpc :GetRoles, ::Google::Protobuf::Empty, ::Tulo::Common::V1::RolesResponse
          rpc :UpsertRole, ::Tulo::Common::V1::UpsertRoleRequest, ::Tulo::Common::V1::UpsertRoleResponse
          rpc :GetRoleById, ::Tulo::Common::V1::RoleIdRequest, ::Tulo::Common::V1::RoleResponse
          rpc :DeleteRoleById, ::Tulo::Common::V1::RoleIdRequest, ::Tulo::Common::V1::CommonDeleteResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
