# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tulo/common/v1/user.proto for package 'tulo.common.v1'

require 'grpc'
require 'tulo/common/v1/user_pb'

module Tulo
  module Common
    module V1
      module UserService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tulo.common.v1.UserService'

          rpc :GetUsers, ::Google::Protobuf::Empty, ::Tulo::Common::V1::UsersResponse
          rpc :UpsertUser, ::Tulo::Common::V1::UpsertUserRequest, ::Tulo::Common::V1::UpsertUserResponse
          rpc :GetUserById, ::Tulo::Common::V1::UserIdRequest, ::Tulo::Common::V1::UserResponse
          rpc :DeleteUserById, ::Tulo::Common::V1::UserIdRequest, ::Tulo::Common::V1::CommonDeleteResponse
          rpc :UserLogin, ::Tulo::Common::V1::LoginInfoRequest, ::Tulo::Common::V1::UserInfoResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
