# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tulo/tasks/v1/report.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/wrappers_pb'
require 'tulo/common/v1/response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tulo/tasks/v1/report.proto", :syntax => :proto3) do
    add_message "tulo.tasks.v1.ReportsResponse" do
      repeated :reports, :message, 1, "tulo.tasks.v1.Report"
    end
    add_message "tulo.tasks.v1.UpsertReportRequest" do
      optional :report, :message, 1, "tulo.tasks.v1.Report"
    end
    add_message "tulo.tasks.v1.UpsertReportResponse" do
      optional :report, :message, 1, "tulo.tasks.v1.Report"
    end
    add_message "tulo.tasks.v1.DocumentIncomingIdRequest" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
    end
    add_message "tulo.tasks.v1.ReportResponse" do
      optional :report, :message, 1, "tulo.tasks.v1.Report"
    end
    add_message "tulo.tasks.v1.ReportIdRequest" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
    end
    add_message "tulo.tasks.v1.Report" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
      optional :document_incoming_id, :message, 2, "google.protobuf.Int64Value"
      optional :employee_id, :message, 3, "google.protobuf.Int64Value"
      optional :role_name, :message, 4, "google.protobuf.StringValue"
      optional :message, :message, 5, "google.protobuf.StringValue"
      optional :created_at, :message, 6, "google.protobuf.StringValue"
      optional :updated_at, :message, 7, "google.protobuf.StringValue"
    end
  end
end

module Tulo
  module Tasks
    module V1
      ReportsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.tasks.v1.ReportsResponse").msgclass
      UpsertReportRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.tasks.v1.UpsertReportRequest").msgclass
      UpsertReportResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.tasks.v1.UpsertReportResponse").msgclass
      DocumentIncomingIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.tasks.v1.DocumentIncomingIdRequest").msgclass
      ReportResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.tasks.v1.ReportResponse").msgclass
      ReportIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.tasks.v1.ReportIdRequest").msgclass
      Report = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.tasks.v1.Report").msgclass
    end
  end
end
