# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tulo/tasks/v1/report.proto for package 'tulo.tasks.v1'

require 'grpc'
require 'tulo/tasks/v1/report_pb'

module Tulo
  module Tasks
    module V1
      module ReportService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tulo.tasks.v1.ReportService'

          rpc :GetReports, ::Google::Protobuf::Empty, ::Tulo::Tasks::V1::ReportsResponse
          rpc :UpsertReport, ::Tulo::Tasks::V1::UpsertReportRequest, ::Tulo::Tasks::V1::UpsertReportResponse
          rpc :GetReportById, ::Tulo::Tasks::V1::ReportIdRequest, ::Tulo::Tasks::V1::ReportResponse
          rpc :GetReportByDocumentIncomingId, ::Tulo::Tasks::V1::DocumentIncomingIdRequest, ::Tulo::Tasks::V1::ReportsResponse
          rpc :DeleteReportById, ::Tulo::Tasks::V1::ReportIdRequest, ::Tulo::Common::V1::CommonDeleteResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
