# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tulo/tasks/v1/task.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/wrappers_pb'
require 'tulo/common/v1/response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tulo/tasks/v1/task.proto", :syntax => :proto3) do
    add_message "tulo.tasks.v1.TasksResponse" do
      repeated :tasks, :message, 1, "tulo.tasks.v1.Task"
    end
    add_message "tulo.tasks.v1.UpsertTaskRequest" do
      optional :task, :message, 1, "tulo.tasks.v1.Task"
    end
    add_message "tulo.tasks.v1.UpsertTaskResponse" do
      optional :task, :message, 1, "tulo.tasks.v1.Task"
    end
    add_message "tulo.tasks.v1.TaskIdRequest" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
    end
    add_message "tulo.tasks.v1.TaskResponse" do
      optional :task, :message, 1, "tulo.tasks.v1.Task"
    end
    add_message "tulo.tasks.v1.Task" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
      optional :document_incoming_id, :message, 2, "google.protobuf.Int64Value"
      optional :department_id, :message, 3, "google.protobuf.Int64Value"
      optional :employee_id, :message, 4, "google.protobuf.Int64Value"
      optional :start_date, :message, 5, "google.protobuf.StringValue"
      optional :end_date, :message, 6, "google.protobuf.StringValue"
      optional :is_approved_by_staff, :message, 7, "google.protobuf.BoolValue"
      optional :is_approved_by_leader, :message, 8, "google.protobuf.BoolValue"
      optional :is_approved_by_manger, :message, 9, "google.protobuf.BoolValue"
      optional :created_at, :message, 10, "google.protobuf.StringValue"
      optional :updated_at, :message, 11, "google.protobuf.StringValue"
    end
  end
end

module Tulo
  module Tasks
    module V1
      TasksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.tasks.v1.TasksResponse").msgclass
      UpsertTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.tasks.v1.UpsertTaskRequest").msgclass
      UpsertTaskResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.tasks.v1.UpsertTaskResponse").msgclass
      TaskIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.tasks.v1.TaskIdRequest").msgclass
      TaskResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.tasks.v1.TaskResponse").msgclass
      Task = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.tasks.v1.Task").msgclass
    end
  end
end
